onboarding = false

[theme]
name = "catppuccin"
auto_switch = false

[ui.toast]
delivery = "system"

[ui.sound]
done_path = "sounds/tuturu.mp3"
request_path = "sounds/sc1-tank-siegeing.mp3"

[ui]
show_agent_labels_on_pane_borders = true

[experimental]
pane_history = false
